services:
  client:
    build: client
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    container_name: coolguys-fe
    restart: always
    depends_on:
      - server

  server:
    container_name: coolguys-be
    restart: always
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
